stages:
  - test
  - build
  - release

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

.android_docker_image:
  image: cirrusci/flutter:2.2.1

test:
  extends: .android_docker_image
  stage: test
  script:
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - coverage/

build_android:
  extends: .android_docker_image
  stage: build
  script: flutter build apk --release --build-number=$CI_PIPELINE_ID
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  only:
    - master

# This build needs an iOS environment.
#build_ios:
#  extends: .android_docker_image
#  stage: build
#  script:
#    - flutter build ios --release --build-number=$CI_PIPELINE_ID
#  artifacts:
#    untracked: true
#  only:
#    - master

release:
  image: inetprocess/gitlab-release
  stage: release
  only:
    - tags && master
  dependencies:
    - build_android
  script:
    - gitlab-release --message 'VORS Android App' build/app/outputs/apk/release/app-release.apk